name: OUR DAILY BRUT
favicon: null
layout_spectrum: 0.24872
typography_spectrum: 0.74957
title: OUR DAILY BRUT
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e0c45c'
    - '#faff8f'
    - '#f5d16f'
    - '#fddc80'
    - '#fdeea2'
  brandStrength: 0.8833589595742524
  lightness: 0.6242678856942803
  saturation: 0.4877569193486124
  rhythmicContrast: 1
purpose: []
